@baseUrl = http://localhost:3333/api
@contentType = application/json

### Create New Comment
POST {{baseUrl}}/comments HTTP/1.1
Content-Type: {{contentType}}

{
  "text": "New Comment for task id 2 by user 6396a84a58dbfb187fc4350e",
  "taskId": 2,
  "userId": "6396a84a58dbfb187fc4350e"
}

### Get Comment By Task ID
GET {{baseUrl}}/comments?taskId=3&page=1 HTTP/1.1

### Create Comment Not Valid
POST {{baseUrl}}/comments HTTP/1.1
Content-Type: {{contentType}}

{
  "text": "New",
  "taskId": "2",
  "userId": "6396a84a58dbfb187fc4350"
}

### Delete Comment
DELETE {{baseUrl}}/comments/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjY2NkZGVjOTIzMDVmYjZhOGRjZDkxZWMiLCJlbWFpbCI6IkRlZV9Cb3lsZUBtYWlsLnJ1Iiwicm9sZSI6ItC30LDQutCw0LfRh9C40LoiLCJpYXQiOjE2NzMxNjEwMzUsImV4cCI6MTY3MzE2NDYzNX0.2t0QXsEEAJKddZtiVDsIHmbj0QVmtSUQCYDytBebrPw
