version: '3.5'
services:
  postgres:
    image: postgres:14-alpine
    container_name: taskforce-postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'taskforce-tasks'
      PGDATA: '/var/lib/postgresql/data/tasks'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d secret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: taskforce-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'test@main.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - './db/pgadmin:/var/lib/pgadmin'
    ports:
      - '8082:80'
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
