@baseUrl = http://localhost:3333/api
@contentType = application/json

### Get Task
GET {{baseUrl}}/task/1 HTTP/1.1


### Create New Task
POST {{baseUrl}}/task HTTP/1.1
Content-Type: {{contentType}}

{
  "title": "New Task",
  "description": "New Task description",
  "category": "детское",
  "userId": "facbf9678dea73a5df67165c",
  "price": 201.98,
  "address": "",
  "tags": ["особенности", "new tag"]
}

### Update Task
PATCH {{baseUrl}}/task/1 HTTP/1.1
Content-Type: {{contentType}}

{
  "status": "Fail",
  "category": "новая 3 категория"
}

### Delete Task
DELETE  {{baseUrl}}/task/1 HTTP/1.1
