@baseUrl = http://localhost:3333/api
@contentType = application/json

### Get Task
GET {{baseUrl}}/tasks/3 HTTP/1.1


### Create New Task Not Valid
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: {{contentType}}

{
  "title": "Lorem ipsum dolor sit ame",
  "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum.",
  "category": "детское",
  "userId": "facbf9678dea73a5df67165c",
  "price": 201.98,
  "address": "Москва Ленинградское ш., 23",
  "executionTerm": "2025-12-12",
  "tags": ["tag", "new"]
}

### Update Task
PATCH {{baseUrl}}/tasks/5 HTTP/1.1
Content-Type: {{contentType}}

{
  "status": "Fail",
  "category": "новая 3 категория"
}

### Delete Task
DELETE  {{baseUrl}}/tasks/14 HTTP/1.1

### Create New Task Not Valid
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: {{contentType}}

{
  "title": "New Task",
  "description": "New Task description",
  "category": "детское",
  "userId": "facbf9678dea73a5df67165c",
  "executionTerm": "2021-12-12",
  "price": 201.988,
  "address": "address",
  "tags": ["особенности"]
}

### Get Tasks Filtering
GET {{baseUrl}}/tasks?category=детское&tags=new,tag&city=Москва

### Get Tasks Sorting
GET {{baseUrl}}/tasks?sortingOption=feedbacks&sortingDirection=asc&city=Владивосток&page=1


### Change Task Status
PATCH {{baseUrl}}/tasks/change-status HTTP/1.1
Content-Type: {{contentType}}

{
  "taskId": 2,
  "newStatus": "Process"
}


### Change Task Status Not Valid
PATCH {{baseUrl}}/tasks/change-status HTTP/1.1
Content-Type: {{contentType}}

{
  "taskId": 9,
  "newStatus": "Cancel"
}
