### Create Review

POST http://localhost:3333/api/review/create HTTP/1.1
Content-Type: application/json

{
  "authorId": "63aebc286a8cf9c071bdda50",
  "contractorId": "63aebc286a8cf9c071bdda51",
  "taskId": 2,
  "text": "Lorem ipsum dolor sit amet, consectetuer adipiscin",
  "rating": 3
}

### Create Review

POST http://localhost:3333/api/review/create HTTP/1.1
Content-Type: application/json

{
  "authorId": "63aebc286a8cf9c071bdda55",
  "contractorId": "63aebc286a8cf9c071bdda51",
  "taskId": 2,
  "text": "Lorem ipsum dolor sit amet, consectetuer adipiscin",
  "rating": 3
}

### Get Review
GET http://localhost:3333/api/review?contractorId=63aebc286a8cf9c071bdda51


### Create Review Not Valid

POST http://localhost:3333/api/review/create HTTP/1.1
Content-Type: application/json

{
  "contractorId": "63aebc286a8cf9c071bdda5",
  "taskId": "2",
  "text": "Lorem ipsum dolor sit amet",
  "rating": "3"
}

### Get Review Not Valid
GET http://localhost:3333/api/review?contractorId=63aebc286a8cf9c071bdda5
