version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: taskforce-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: taskforce-users
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: taskforce-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongodb:27017/
