@baseUrl = http://localhost:3333/api
@contentType = application/json

### Create New Feedback
POST {{baseUrl}}/feedbacks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MwZmQ3ZjY4NDY3YTkwMjEyNjVlNmUiLCJlbWFpbCI6InVzZXIxQG1haWwuY29tIiwicm9sZSI6ItC30LDQutCw0LfRh9C40LoiLCJpYXQiOjE2NzM2ODgwNzksImV4cCI6MTY3MzY5MTY3OX0.WSkVbgOQ1ZJ3iMrS8Qlv3hzkmLh_cqmr32PU0IyLmYs
Content-Type: {{contentType}}

{
  "text": "New Feedback",
  "taskId": 2,
}

### Get feedbacks for Task
GET {{baseUrl}}/feedbacks?taskId=2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MwZmQ3ZjY4NDY3YTkwMjEyNjVlNmUiLCJlbWFpbCI6InVzZXIxQG1haWwuY29tIiwicm9sZSI6ItC30LDQutCw0LfRh9C40LoiLCJpYXQiOjE2NzM2ODAyOTUsImV4cCI6MTY3MzY4Mzg5NX0.-i0FTRWL_qdMUVJLWJ05lgDg5JfeCo7TtigArjow2T

### Create Feedback Not Valid
POST {{baseUrl}}/feedbacks HTTP/1.1
Content-Type: {{contentType}}

{
  "text": "Not Valid Feedback",
  "price": -234.789,
  "taskId": "2",
}
