@baseUrl = http://localhost:3330/api
@contentType = application/json

### Create New Task
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MzYWQ1M2Y0ZjMzZjgyZGVkZGY1MTEiLCJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJyb2xlIjoi0LjRgdC_0L7Qu9C90LjRgtC10LvRjCIsImlhdCI6MTY3Mzc3MjkzOSwiZXhwIjoxNjczNzc2NTM5fQ.bRT1wNsGBjP2hS_Y6Fc6V7tBhNAfwu8MNqDfVslFzjM

{
  "title": "Lorem ipsum dolor sit ame",
  "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum.",
  "category": "детское",
  "userId": "facbf9678dea73a5df67165c",
  "price": 201.98,
  "address": "Москва Ленинградское ш., 23",
  "executionTerm": "2025-12-12",
  "tags": ["tag", "new"]
}

### Update Task
PATCH {{baseUrl}}/tasks/1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YWQyYjhhMDI1YzUxN2RmY2Y1YzRjY2IiLCJlbWFpbCI6IkRlb24uQmFydG9uQHlhbmRleC5ydSIsInJvbGUiOiLQt9Cw0LrQsNC30YfQuNC6IiwiaWF0IjoxNjczNzczODI1LCJleHAiOjE2NzM3Nzc0MjV9.Oih3pnc1JAccFLdNUOeMh6O-Yvy9N3rz4iNzotKAOUQ

{
  "category": "новая 3 категория"
}

### Delete Task
DELETE  {{baseUrl}}/tasks/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YWQyYjhhMDI1YzUxN2RmY2Y1YzRjY2IiLCJlbWFpbCI6IkRlb24uQmFydG9uQHlhbmRleC5ydSIsInJvbGUiOiLQt9Cw0LrQsNC30YfQuNC6IiwiaWF0IjoxNjczNzc0MzA3LCJleHAiOjE2NzM3Nzc5MDd9.zW55OCSLIWF5hjXkbKwO646wOAFOeThcsd1XLm4bc5o

### Change Task Status
PATCH {{baseUrl}}/tasks/change-status HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDMzMmMxNDQwMjVlMWJlYWM0ZDQxM2MiLCJlbWFpbCI6IkdpbGxpYW5fSGVyem9nMTBAaG90bWFpbC5jb20iLCJyb2xlIjoi0LfQsNC60LDQt9GH0LjQuiIsImlhdCI6MTY3Mzc1Mjk3NywiZXhwIjoxNjczNzU2NTc3fQ.XJBzWdJ04GIGZCy1LmINBByz_N1aAanYRNKRJIcmQGc

{
  "taskId": 16,
  "newStatus": "Fail"
}

### Assign Contractor
PATCH {{baseUrl}}/tasks/assign-contractor HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiM2ZiYTBhYzkxMWQ1ZmNiMGNmOWQzY2YiLCJlbWFpbCI6IldpbGxvdy5SYXlub3JAZ21haWwuY29tIiwicm9sZSI6ItC30LDQutCw0LfRh9C40LoiLCJpYXQiOjE2NzM3NTQ5OTAsImV4cCI6MTY3Mzc1ODU5MH0.eGJzbVtOtOUoz88FJm24mq3J8x045dbEW_jYkfER7jA

{
  "taskId": 18,
  "contractorId": "52e59a5fa464c2dddb35ddfb"
}

### Get My Tasks
GET {{baseUrl}}/tasks/my-tasks?status=Complete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiM2ZiYTBhYzkxMWQ1ZmNiMGNmOWQzY2YiLCJlbWFpbCI6IldpbGxvdy5SYXlub3JAZ21haWwuY29tIiwicm9sZSI6ItC30LDQutCw0LfRh9C40LoiLCJpYXQiOjE2NzM3NTQ5OTAsImV4cCI6MTY3Mzc1ODU5MH0.eGJzbVtOtOUoz88FJm24mq3J8x045dbEW_jYkfER7jA

### Get Notify
#?lastNotify=2023-01-13
GET {{baseUrl}}/tasks/notify HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MzOTRjNzhjODYwOGNkNTg4MmUxMjgiLCJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJyb2xlIjoi0LjRgdC_0L7Qu9C90LjRgtC10LvRjCIsImlhdCI6MTY3Mzc2MjAyMSwiZXhwIjoxNjczNzY1NjIxfQ.qlra3njt4jcxzGw0gYDEdq7LuSi2yRjUBcaxcY1-Jdk

### Get Task
GET {{baseUrl}}/tasks/43 HTTP/1.1

### Get Tasks Filtering
GET {{baseUrl}}/tasks?category=Автомобильное&city=Москва

### Get Tasks Sorting
GET {{baseUrl}}/tasks?sortingOption=feedbacks&sortingDirection=asc&city=Владивосток&page=1
