@baseUrl = http://localhost:3333/api
@contentType = application/json
@accessToken = {{login.response.body.accessToken}}


### Register User
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "user",
  "email": "user54@mail.com",
  "password": "secret",
  "city": "Москва",
  "birthday": "2020-11-20",
  "role": "заказчик"
}


### Login User
# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "Domingo_Zieme53@mail.ru",
  "password": "secret"
}


### Get User
GET {{baseUrl}}/auth/63aebc286a8cf9c071bdda50
Authorization: Bearer {{accessToken}}

### Create User Bad Request
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "us",
  "email": "usermail.com",
  "password": "secret",
  "city": "Москва",
  "birthday": "2020-11-20"
}

### Change Password
PATCH {{baseUrl}}/auth/63b02297c7d1400af65e1106/change-password
Content-Type: {{contentType}}

{
  "currentPassword": "secret",
  "newPassword": "newSecret"
}

### Login User New Password
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "user54@mail.com",
  "password": "secret"
}

### Change Password
PATCH {{baseUrl}}/auth/63b02297c7d1400af65e1106/change-password
Content-Type: {{contentType}}

{
  "currentPassword": "newSecret",
  "newPassword": "secret"
}
