@baseUrl = http://localhost:3333/api
@contentType = application/json
@userId = {{login.response.body.id}}


### Register User
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "user",
  "email": "user@mail.com",
  "password": "secret",
  "city": "Москва",
  "birthday": "2020-11-20",
  "role": "customer"
}


### Login User
# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "user@mail.com",
  "password": "secret"
}


### Get User
GET {{baseUrl}}/auth/{{userId}}

### Create User Bad Request
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "us",
  "email": "usermail.com",
  "password": "secret",
  "city": "Москва",
  "birthday": "2020-11-20"
}
