version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbirmq-notify
    ports:
      - 5672:5672
      - 8084:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: fake-smtp-notify
    ports:
      - 5025:5025
      - 8083:5080

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-notify
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: taskforce-notify
    ports:
      - 27018:27017
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-notify
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongodb:27017/
